server:
  port: 9092

keycloak:
  realm: metaq-cn
  auth-server-url: http://localhost:8080/auth
  resource: app-authz-security-api
  ssl-required: external
#  #使用realm级别还是应用级别的角色控制
  use-resource-role-mappings: false
  bearer-only: true
#  credentials:
#    secret: ae6ce704-f9b9-4e68-ac3e-9647b47b3f23

logging:
  level:
    org:
      keycloak: DEBUG