server:
  port: 9093

keycloak:
  realm: metaq-cn
  auth-server-url: http://localhost:8080/auth
  resource: app-authz-security-webapi
  ssl-required: external
  credentials:
    secret: 77ee5059-352f-41c9-a3f1-629830e53f93
  #使用realm级别还是应用级别的角色控制
  use-resource-role-mappings: false
  bearer-only: false
  #应用同时提供web页面跟Restful API服务时需设置为true，Keycloak会根据请求的方式，将未通过认证的请求重定向到登录页或者直接返回401状态码
  autodetect-bearer-only: true

spring:
  thymeleaf:
    cache: false
    prefix: classpath:/views/
    mode: HTML

logging:
  level:
    org:
      keycloak: DEBUG